// This file is auto-generated by scripts/generate-blog-index.mjs
// Do not edit manually. Run "npm run content:gen" to regenerate.

export type BlogIndexItem = {
  slug: string;
  title: string;
  description: string;
  date: string;
  tags: string[];
  intent?: string;
  cover?: string;
  readingMinutes: number;
};

export const blogIndex: BlogIndexItem[] = [
  {
    "slug": "natural-light-full-final",
    "title": "Важность естественного освещения во всех помещениях жилого дома",
    "description": "Почему каждый уголок дома — от гостиной до санузла — должен получать дневной свет, и как это влияет на здоровье, комфорт и даже философский взгляд на пространство.",
    "date": "2026-02-10",
    "tags": [
      "освещение",
      "естественный свет",
      "дом",
      "интерьер",
      "здоровье"
    ],
    "intent": "informational",
    "cover": "/showroom/bathroom/odnoetazhniki-showroom-bathroom-02.jpg",
    "readingMinutes": 3
  },
  {
    "slug": "plita-na-penoplaste",
    "title": "Плита на ЭППС для каркасного дома на пучинистых грунтах Подмосковья",
    "description": "Как работает мелкозаглубленная ЖБ-плита на пенопласте, какие толщины, и почему это устойчивее свай на пучинистых грунтах.",
    "date": "2026-02-09",
    "tags": [
      "фундамент",
      "ЭППС",
      "Подмосковье",
      "каркасный дом"
    ],
    "readingMinutes": 3
  },
  {
    "slug": "teplovizor-obsledovanie",
    "title": "Почему в доме холодно: тепловизионное обследование",
    "description": "Как тепловизор находит утечки тепла, мостики холода и продувания — и как это снижает счета за отопление.",
    "date": "2026-02-09",
    "tags": [
      "тепловизор",
      "энергоэффективность",
      "обследование"
    ],
    "readingMinutes": 4
  },
  {
    "slug": "ventilyaciya-svezhest-chistota",
    "title": "Свежесть против чистоты: почему вентиляция может «убивать» воздух",
    "description": "Разбираем разницу между чистотой и свежестью, ионизацию, фильтры и обслуживание. Когда механика нужна, а когда лучше простая естественная схема.",
    "date": "2026-02-09",
    "tags": [
      "вентиляция",
      "качество воздуха",
      "инженерные системы"
    ],
    "readingMinutes": 9
  }
];
