// This file is auto-generated by scripts/generate-showroom-manifest.mjs
// Do not edit manually. Run "npm run content:gen" to regenerate.

export type ShowroomSlide = {
  src: string;
  category: string;
  alt: string;
  caption: string;
  tags: string[];
  blogSlug?: string;
  featureKey?: string;
};

export const showroomSlides: ShowroomSlide[] = [
  {
    "src": "/showroom/bathroom/odnoetazhniki-showroom-bathroom-01.jpg",
    "category": "bathroom",
    "alt": "Шоурум одноэтажного дома: санузел и душ",
    "caption": "Санузел и душ",
    "tags": []
  },
  {
    "src": "/showroom/bathroom/odnoetazhniki-showroom-bathroom-02.jpg",
    "category": "bathroom",
    "alt": "Шоурум одноэтажного дома: санузел и душ",
    "caption": "Санузел и душ",
    "tags": []
  },
  {
    "src": "/showroom/bathroom/odnoetazhniki-showroom-bathroom-03.jpg",
    "category": "bathroom",
    "alt": "Шоурум одноэтажного дома: санузел и душ",
    "caption": "Санузел и душ",
    "tags": []
  },
  {
    "src": "/showroom/bathroom/odnoetazhniki-showroom-bathroom-04.jpg",
    "category": "bathroom",
    "alt": "Шоурум одноэтажного дома: санузел и душ",
    "caption": "Санузел и душ",
    "tags": []
  },
  {
    "src": "/showroom/bathroom/odnoetazhniki-showroom-bathroom-05.jpg",
    "category": "bathroom",
    "alt": "Шоурум одноэтажного дома: санузел и душ",
    "caption": "Санузел и душ",
    "tags": []
  },
  {
    "src": "/showroom/bathroom/odnoetazhniki-showroom-bathroom-06.jpg",
    "category": "bathroom",
    "alt": "Шоурум одноэтажного дома: санузел и душ",
    "caption": "Санузел и душ",
    "tags": []
  },
  {
    "src": "/showroom/bathroom/odnoetazhniki-showroom-bathroom-07.jpg",
    "category": "bathroom",
    "alt": "Шоурум одноэтажного дома: санузел и душ",
    "caption": "Санузел и душ",
    "tags": []
  },
  {
    "src": "/showroom/bathroom/odnoetazhniki-showroom-bathroom-08.jpg",
    "category": "bathroom",
    "alt": "Шоурум одноэтажного дома: санузел и душ",
    "caption": "Санузел и душ",
    "tags": []
  },
  {
    "src": "/showroom/bedroom/odnoetazhniki-showroom-bedroom-01.jpg",
    "category": "bedroom",
    "alt": "Шоурум одноэтажного дома: спальня",
    "caption": "Спальня",
    "tags": []
  },
  {
    "src": "/showroom/bedroom/odnoetazhniki-showroom-bedroom-02.jpg",
    "category": "bedroom",
    "alt": "Шоурум одноэтажного дома: спальня",
    "caption": "Спальня",
    "tags": []
  },
  {
    "src": "/showroom/exterior/odnoetazhniki-showroom-exterior-01.jpg",
    "category": "exterior",
    "alt": "Шоурум одноэтажного дома: фасад и внешний вид",
    "caption": "Фасад и внешний вид",
    "tags": []
  },
  {
    "src": "/showroom/exterior/odnoetazhniki-showroom-exterior-02.jpg",
    "category": "exterior",
    "alt": "Шоурум одноэтажного дома: фасад и внешний вид",
    "caption": "Фасад и внешний вид",
    "tags": []
  },
  {
    "src": "/showroom/interior/odnoetazhniki-showroom-interior-01.jpg",
    "category": "interior",
    "alt": "Шоурум одноэтажного дома: интерьер и планировка",
    "caption": "Интерьер шоурума",
    "tags": []
  },
  {
    "src": "/showroom/interior/odnoetazhniki-showroom-interior-02.jpg",
    "category": "interior",
    "alt": "Шоурум одноэтажного дома: интерьер и планировка",
    "caption": "Интерьер шоурума",
    "tags": []
  },
  {
    "src": "/showroom/interior/odnoetazhniki-showroom-interior-03.jpg",
    "category": "interior",
    "alt": "Шоурум одноэтажного дома: интерьер и планировка",
    "caption": "Интерьер шоурума",
    "tags": []
  },
  {
    "src": "/showroom/interior/odnoetazhniki-showroom-interior-04.jpg",
    "category": "interior",
    "alt": "Шоурум одноэтажного дома: интерьер и планировка",
    "caption": "Интерьер шоурума",
    "tags": []
  },
  {
    "src": "/showroom/kitchen/odnoetazhniki-showroom-kitchen-01.jpg",
    "category": "kitchen",
    "alt": "Шоурум одноэтажного дома: кухня-гостиная",
    "caption": "Кухня-гостиная",
    "tags": []
  },
  {
    "src": "/showroom/landscape/odnoetazhniki-showroom-landscape-01.jpg",
    "category": "landscape",
    "alt": "Шоурум одноэтажного дома: участок и окружение",
    "caption": "Участок и окружение",
    "tags": []
  },
  {
    "src": "/showroom/landscape/odnoetazhniki-showroom-landscape-02.jpg",
    "category": "landscape",
    "alt": "Шоурум одноэтажного дома: участок и окружение",
    "caption": "Участок и окружение",
    "tags": []
  },
  {
    "src": "/showroom/landscape/odnoetazhniki-showroom-landscape-03.jpg",
    "category": "landscape",
    "alt": "Шоурум одноэтажного дома: участок и окружение",
    "caption": "Участок и окружение",
    "tags": []
  },
  {
    "src": "/showroom/plan/odnoetazhniki-showroom-plan-01.jpg",
    "category": "plan",
    "alt": "Шоурум одноэтажного дома: планировка",
    "caption": "Планировка",
    "tags": []
  }
];
